vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /uploads/property_images
            upload_destination: '%kernel.project_dir%/public/uploads/property_images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

